### ISSUE TITLE
ornement is compromised when adding a bar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [realisim/realisim#5]
```
What steps will reproduce the problem?
1. have something like this with ornement over m and p notes srg|m|p
2. add a bar after m
3. the ornement is broken

What is the expected output? What do you see instead?
I would expect the ornement to follow.

Please use labels and text to provide additional information.


```

Original issue reported on code.google.com by `pierreolivier.beaudoin@gmail.com` on 1 May 2015 at 11:55

**Comment by realisim** [comment]
This was fixed in an earlier commit... The result is awkward (see attached), i guess the real issue is about the layout.
![issue5](https://cloud.githubusercontent.com/assets/13717897/11461622/d5453576-96d4-11e5-9a6f-ee132718c2c8.png)
